DROP SEQUENCE SEQ_CHANEL;
CREATE SEQUENCE SEQ_CHANEL NOCACHE NOCYCLE;

DROP TABLE CHANEL CASCADE CONSTRAINT;
CREATE TABLE CHANEL(
    NO              NUMBER          PRIMARY KEY
    , PRODUCT       VARCHAR2(100)   NOT NULL
    , PRICE         VARCHAR2(100)   NOT NULL
    , QUANTITY      NUMBER          
    , CREATE_DATE   TIMESTAMP       DEFAULT SYSDATE
    , DEL_YN        CHAR(1)       DEFAULT 'Y' CHECK(DEL_YN IN('Y','N'))
);
-- 화장품 등록
INSERT INTO CHANEL(NO,PRODUCT,PRICE,QUANTITY) VALUES(SEQ_CHANEL.NEXTVAL, 'LIPSTICK', '50000', 100);
-- 화장품 수정
UPDATE CHANEL SET PRODUCT = 'BB크림' WHERE NO = 1;
-- 화장품 삭제
UPDATE CHANEL SET DEL_YN = 'N' WHERE NO = 1;
-- 화장품 단건목록
SELECT * FROM CHANEL WHERE NO = 1;
-- 판매중 화장품 검색
SELECT * FROM CHANEL WHERE DEL_YN = 'N';
-- 단종된 화장품 검색
SELECT * FROM CHANEL WHERE DEL_YN = 'Y';
-- 화장품 전체검색
SELECT * FROM CHANEL;