DROP SEQUENCE SEQ_MOVIE;
CREATE SEQUENCE SEQ_MOVIE NOCACHE NOCYCLE;

DROP TABLE MOVIE CASCADE CONSTRAINTS;
CREATE TABLE MOVIE (
    NO              NUMBER          PRIMARY KEY
    , TITLE         VARCHAR2(100)   UNIQUE
    , MAINCHA       VARCHAR2(100)   NOT NULL
    , GENDER        CHAR(1)         CHECK(GENDER IN ('M','F'))
    , RELESE_DATE   TIMESTAMP       DEFAULT SYSDATE
    , PLAY_YN       CHAR(1)         DEFAULT 'Y' CHECK(PLAY_YN IN ('Y','N'))
);
//등록 (제목,주인공,성별,개봉일)
INSERT INTO MOVIE(NO, TITLE, MAINCHA, GENDER, RELESE_DATE) VALUES(SEQ_MOVIE.NEXTVAL,'바람의 나우시카', '나우시카', 'F', '001230');
//수정 (주인공,성별)
UPDATE MOVIE SET MAINCHA = '냐우시카' WHERE NO = 1 AND GENDER = 'F';
//삭제 (상영여부)
UPDATE MOVIE SET PLAY_YN = 'Y';

SELECT * FROM MOVIE;

SELECT * FROM MOVIE WHERE NO = 1 ORDER BY TITLE;
COMMIT;